#!/bin/sh
# postinst script for pardus-config
#

set -e

case "$1" in
    configure)
        update-rc.d pardus-xorg-conf defaults
        update-initramfs -u 
        ;;

    *)
        ;;
esac

exit 0

